[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "quantum-sim"
version = "0.1.0"
description = "Mon projet de simulation quantique"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []


[project.scripts]
quantum-sim = "quantum_sim.__main__:main"
homepage = "https://github.com/UgoW/QUANTUM-SIM"

[tool.poetry]
packages = [{ include = "quantum_sim", from = "src" }]

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"